import type { Metadata } from "next";

export const metadata : Metadata = {
    title: {
        absolute:"About",
    },
    description: "Generated by create next app",
  
  
  };
export default function AboutLayout({children}:{
    children: React.ReactNode;
})


{
    return(
        <>
        <h2>Groupe auth </h2>
        {children}
        </>
    )
}